### ISSUE TITLE
建议增加创建表 和 删除 表的 功能

### ISSUE THREAD

**Issue by const-undefined-man** [AspenLuoQiang/hyoga-mysql#10]
建议增加，找了很多关于nodejs的查询构造器，感觉你这个写的还挺好，但是我需要用到创建表和删除表的功能，你这里没有。

是否可以考虑一下，新增一些功能呢？比如：创建表，创建表+字段，表重命名，删除表，更改表的字符集 等；还有表中字段的一些常用操作，添加字段，删除字段，字段重命名，更新字段类型 等。。。

我找了一个有的，你可以参考一下： https://github.com/dresende/node-sql-query 

希望可以考虑
`
mysql.table('tableName').create();

mysql.table('tableName').field({...}).create();

mysql.table('tableName').delete();
`

**Comment by guyue88** [comment]
感谢你的建议，我这边会抽空考虑增加一下，你也可以直接使用 query方法直接执行sql语句创建表。
