### ISSUE TITLE
service内一个方法执行多次sql语句，返回结果错乱问题

### ISSUE THREAD

**Issue by heibaikn** [AspenLuoQiang/hyoga-mysql#11]
node version :  v12.16.1
@hyoga/egg-mysql version: "^1.0.9",

问题：
total 得到mysql的链接
result 得到count的计算结果
![image](https://user-images.githubusercontent.com/17714507/116180190-13b5cf00-a74b-11eb-84c2-6011b130555b.png)

期望：
total  得到count的计算结果
result  得到分页的计算结果

**Comment by heibaikn** [comment]
` 
 /**
   * 查询统计数
   * @example mysql.table('article_posts').count().select(), count()后可拼接field()和where()
   * @return {Mysql} 实例
   */  
   count(): Mysql {
    this._count = true;
    return this;
  }
`

查看源码发现   count() 后面需要加 .select() 才会query sql ， 期望owner添加mysql.count() 文档

**Comment by guyue88** [comment]
@heibaikn 我看看的
